- name: 添加 Docker yum 仓库
  shell: >
    yum-config-manager --add-repo {{docker_yum_repo}}

# yum list docker-ce --showduplicates | sort -r
- name: 安装 Docker
  yum:
    name: 
    - docker-ce-{{docker_version}}
    - docker-ce-cli-{{docker_version}}
    - docker-compose-plugin-2.6.0-3.el7
    - containerd.io-1.6.6-3.1.el7
    state: present
  when:
  - 'INSTALL_SOURCE != "offline"'
