
# to clean 'kube_master' nodes
- name: reset kubenertes cluster
  shell: kubeadm reset -f
  ignore_errors: true
  when: "inventory_hostname in groups['kube_master']"


- name: stop and disable kube_master service
  service: name={{ item }} state=stopped enabled=no
  with_items:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - docker
  - containerd
  ignore_errors: true
  when: "inventory_hostname in groups['kube_master']"

- name: remove apt  kube_master service
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - kubeadm
    - kubelet
    - kubectl
    state: absent
  ignore_errors: true


- name: remove files and dirs of 'kube_master' nodes
  file: name={{ item }} state=absent
  with_items:
  - "/var/run/kubernetes"
  - "/etc/kubernetes"
  - "/var/lib/etcd"
  - "/etc/kubelet/"
  - "/etc/cni"
  - "/opt/cni"
  - "/var/etcd"
  - "/etc/systemd/system/kube-apiserver.service"
  - "/etc/systemd/system/kube-controller-manager.service"
  - "/etc/systemd/system/kube-scheduler.service"
  when: "inventory_hostname in groups['kube_master']"
