- name: 添加 Kubernetes yum 仓库
  yum_repository:
    name: kubernetes
    file: kubernetes
    description: Kubernetes
    baseurl: "{{ kubernetes_yum_repo }}"
    enabled: no
    gpgcheck: no
    state: present

- name: "安装 kubelet-{{ kube_version }} kubectl-{{ kube_version }}"
  yum:
    name:
    - "kubelet-{{ kube_version }}"
    - "kubectl-{{ kube_version }}"
    state: present
    enablerepo: kubernetes
  when:
  - 'INSTALL_SOURCE == "offline"'

- name: "安装 kubeadm-{{ kube_version }}"
  yum:
    name:
    - "kubeadm-{{ kube_version }}"
    state: present
    enablerepo: kubernetes
  when:
  - 'INSTALL_SOURCE != "offline"'


- block:
  - name: 离线下载Kubernetes rpm 包
    copy:
      src: "{{ base_dir }}/offline/packages/rpm/kubernetes-{{ kube_version }}.tgz"
      dest: "/tmp"
  - name: 解压kubernetes 安装包
    shell: >
      tar -xvf /tmp/kubernetes-1.20.15.tgz -C /tmp
  - name: 离线安装 kubernetes
    shell: >
      yum install -y /tmp/kubernetes/*.rpm
  when:
  - 'INSTALL_SOURCE == "offline"'


