- name: 删除过期的token 参数
  shell: |
    # 获取token的list
    # kubeadm token list
    kubeadm token list|grep -v TOKEN |awk '{print $1}'|xargs -i kubeadm token delete {}
  ignore_errors: true
- name: 获取kubeadm token 信息
  shell: |
    kubeadm token create --print-join-command
  register: kubeadm_token
- name: 获取第一个节点的LB 地址
  shell: |
   echo "{{ current_host_ip }} lb.kubernetes.com"
  register: lb_address
