# 初始化master节点
- hosts: 
  - kube_master
  roles:
  - { role: os-harden, when: "OS_HARDEN|bool" }
  - { role: chrony, when: "groups['chrony']|length > 0" }
  - prepare
  - { role: runtime }
  - kube-master