# 初始化master节点
- hosts:
  - kube_node
  - kube_master
  roles:
  - { role: os-harden, when: "OS_HARDEN|bool" }
  - { role: chrony, when: "groups['chrony']|length > 0" }
  - prepare
  - { role: runtime }

- hosts:
  - kube_master
  roles:
  - kube-master


- hosts:
  - kube_node
  - kube_master
  roles:
  - kube-node


- hosts:
  - kube_master
  roles:
  - manifests
