- name: 添加 Kubernetes yum 仓库
  shell: |
    yum-config-manager --add-repo {{kubernetes_yum_repo}}
  ignore_errors: true
  when:
  - 'INSTALL_SOURCE != "offline"'

- name: "安装 kubelet-{{ kube_version }} kubectl-{{ kube_version }}"
  yum:
    name:
    - "kubelet-{{ kube_version }}"
    - "kubectl-{{ kube_version }}"
    state: present
    enablerepo: kubernetes
  when:
  - 'INSTALL_SOURCE != "offline"'
- name: "安装 kubeadm-{{ kube_version }}"
  yum:
    name:
    - "kubeadm-{{ kube_version }}"
    state: present
    enablerepo: kubernetes
  when:
  - 'INSTALL_SOURCE != "offline"'
